import type { SourceType } from "@/lib/store";

export type SourcePresetCategory =
  | "ai-official"
  | "community"
  | "domestic-tech"
  | "content-social"
  | "product-updates"
  | "jobs";

export type SourcePreset = {
  id: string;
  title: string;
  description: string;
  url: string;
  sourceType: SourceType;
  category: SourcePresetCategory;
  configJson?: Record<string, unknown> | null;
};

export const sourcePresets: SourcePreset[] = [
  {
    id: "openai-blog",
    title: "OpenAI Blog",
    description: "Official OpenAI product, research, and company updates.",
    url: "https://openai.com/blog/rss.xml",
    sourceType: "RSS",
    category: "ai-official",
  },
  {
    id: "openai-changelog",
    title: "OpenAI Platform Changelog",
    description: "Official OpenAI API and platform change notes.",
    url: "https://platform.openai.com/docs/changelog",
    sourceType: "UPDATE",
    category: "ai-official",
  },
  {
    id: "anthropic-news",
    title: "Anthropic News",
    description: "Official Anthropic announcements and Claude product news.",
    url: "https://www.anthropic.com/news",
    sourceType: "STRUCTURED",
    category: "ai-official",
  },
  {
    id: "anthropic-release-notes",
    title: "Claude Release Notes",
    description: "Anthropic release notes for Claude and API-facing updates.",
    url: "https://docs.anthropic.com/en/release-notes/overview",
    sourceType: "UPDATE",
    category: "ai-official",
  },
  {
    id: "google-deepmind-blog",
    title: "Google DeepMind Blog",
    description: "Research and product updates from Google DeepMind.",
    url: "https://deepmind.google/discover/blog/",
    sourceType: "STRUCTURED",
    category: "ai-official",
  },
  {
    id: "cursor-changelog",
    title: "Cursor Changelog",
    description: "Cursor editor product releases and feature updates.",
    url: "https://cursor.com/changelog",
    sourceType: "UPDATE",
    category: "ai-official",
  },
  {
    id: "github-blog",
    title: "GitHub Blog",
    description: "GitHub product, engineering, and ecosystem updates.",
    url: "https://github.blog/feed/",
    sourceType: "RSS",
    category: "ai-official",
  },
  {
    id: "github-changelog",
    title: "GitHub Changelog",
    description: "GitHub platform changelog and developer-facing releases.",
    url: "https://github.blog/changelog/feed/",
    sourceType: "RSS",
    category: "ai-official",
  },
  {
    id: "vercel-changelog",
    title: "Vercel Changelog",
    description: "Vercel platform releases and product changes.",
    url: "https://vercel.com/changelog",
    sourceType: "UPDATE",
    category: "ai-official",
  },
  {
    id: "supabase-blog",
    title: "Supabase Blog",
    description: "Supabase product, database, and developer platform updates.",
    url: "https://supabase.com/blog/rss.xml",
    sourceType: "RSS",
    category: "ai-official",
  },
  {
    id: "supabase-changelog",
    title: "Supabase Changelog",
    description: "Supabase product changelog and release notes.",
    url: "https://supabase.com/changelog",
    sourceType: "UPDATE",
    category: "ai-official",
  },
  {
    id: "cloudflare-blog",
    title: "Cloudflare Blog",
    description: "Cloudflare product, infrastructure, and developer updates.",
    url: "https://blog.cloudflare.com/rss/",
    sourceType: "RSS",
    category: "ai-official",
  },
  {
    id: "hacker-news-discovery",
    title: "Hacker News Search",
    description: "HN discussion discovery using the task's monitoring queries.",
    url: "radar://community-discovery/hacker-news",
    sourceType: "COMMUNITY_DISCOVERY",
    category: "community",
    configJson: { providers: ["hacker-news"] },
  },
  {
    id: "product-hunt-discovery",
    title: "Product Hunt Discovery",
    description: "Product Hunt launch discovery using the task's monitoring queries.",
    url: "radar://community-discovery/product-hunt",
    sourceType: "COMMUNITY_DISCOVERY",
    category: "community",
    configJson: { providers: ["product-hunt"] },
  },
  {
    id: "reddit-discovery",
    title: "Reddit Search",
    description: "Reddit discussion discovery using the task's monitoring queries.",
    url: "radar://community-discovery/reddit",
    sourceType: "COMMUNITY_DISCOVERY",
    category: "community",
    configJson: { providers: ["reddit"] },
  },
  {
    id: "github-trending",
    title: "GitHub Trending",
    description: "Trending repositories and open-source momentum signals.",
    url: "https://github.com/trending",
    sourceType: "STRUCTURED",
    category: "community",
  },
  {
    id: "lobsters",
    title: "Lobsters",
    description: "Technical community links and discussion.",
    url: "https://lobste.rs/rss",
    sourceType: "RSS",
    category: "community",
  },
  {
    id: "dev-to",
    title: "Dev.to",
    description: "Developer community posts and tutorials.",
    url: "https://dev.to/feed",
    sourceType: "RSS",
    category: "community",
  },
  {
    id: "juejin",
    title: "掘金",
    description: "Domestic China developer articles and technology discussions.",
    url: "https://juejin.cn/",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "v2ex-tech",
    title: "V2EX 技术节点",
    description: "Domestic developer forum topics and community signals.",
    url: "https://www.v2ex.com/?tab=tech",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "oschina-news",
    title: "OSCHINA 开源中国",
    description: "Open-source and developer ecosystem news in China.",
    url: "https://www.oschina.net/news",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "segmentfault-blogs",
    title: "SegmentFault",
    description: "Domestic developer blogs and technical posts.",
    url: "https://segmentfault.com/blogs",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "csdn-blog",
    title: "CSDN",
    description: "Domestic developer blog posts and technical articles.",
    url: "https://blog.csdn.net/",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "infoq-cn-ai",
    title: "InfoQ 中文 AI",
    description: "Chinese technology analysis and AI topic coverage.",
    url: "https://www.infoq.cn/topic/AI",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "jiqizhixin",
    title: "机器之心",
    description: "AI research, industry, and product news in Chinese.",
    url: "https://www.jiqizhixin.com/",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "qbitai",
    title: "量子位",
    description: "AI industry news and product signals in Chinese.",
    url: "https://www.qbitai.com/",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "36kr-tech",
    title: "36氪科技",
    description: "China technology, startup, and business coverage.",
    url: "https://36kr.com/information/technology/",
    sourceType: "STRUCTURED",
    category: "domestic-tech",
  },
  {
    id: "bilibili-discovery",
    title: "B站搜索发现",
    description: "Bilibili discovery using the task's monitoring queries.",
    url: "radar://social-discovery/bilibili",
    sourceType: "SOCIAL_DISCOVERY",
    category: "content-social",
    configJson: { providers: ["bilibili"] },
  },
  {
    id: "weibo-discovery",
    title: "微博搜索发现",
    description: "Weibo discovery using the task's monitoring queries.",
    url: "radar://social-discovery/weibo",
    sourceType: "SOCIAL_DISCOVERY",
    category: "content-social",
    configJson: { providers: ["weibo"] },
  },
  {
    id: "zhihu-search",
    title: "知乎搜索",
    description: "Zhihu content search page for monitoring topic discovery.",
    url: "https://www.zhihu.com/search?type=content&q=AI",
    sourceType: "STRUCTURED",
    category: "content-social",
  },
  {
    id: "xiaohongshu-search",
    title: "小红书搜索",
    description: "Xiaohongshu search page for consumer and product discussion signals.",
    url: "https://www.xiaohongshu.com/search_result?keyword=AI",
    sourceType: "STRUCTURED",
    category: "content-social",
  },
  {
    id: "linear-changelog",
    title: "Linear Changelog",
    description: "Linear product releases and workflow updates.",
    url: "https://linear.app/changelog",
    sourceType: "UPDATE",
    category: "product-updates",
  },
  {
    id: "notion-releases",
    title: "Notion Releases",
    description: "Notion product releases and feature updates.",
    url: "https://www.notion.com/releases",
    sourceType: "UPDATE",
    category: "product-updates",
  },
  {
    id: "slack-changelog",
    title: "Slack Changelog",
    description: "Slack platform and developer changelog.",
    url: "https://docs.slack.dev/changelog/",
    sourceType: "UPDATE",
    category: "product-updates",
  },
  {
    id: "stripe-blog",
    title: "Stripe Blog",
    description: "Stripe product, platform, and company updates.",
    url: "https://stripe.com/blog",
    sourceType: "STRUCTURED",
    category: "product-updates",
  },
  {
    id: "stripe-changelog",
    title: "Stripe Changelog",
    description: "Stripe API and product changelog.",
    url: "https://docs.stripe.com/changelog",
    sourceType: "UPDATE",
    category: "product-updates",
  },
  {
    id: "shopify-engineering",
    title: "Shopify Engineering",
    description: "Engineering posts and platform updates from Shopify.",
    url: "https://shopify.engineering/",
    sourceType: "STRUCTURED",
    category: "product-updates",
  },
  {
    id: "microsoft-devblogs",
    title: "Microsoft Developer Blogs",
    description: "Microsoft developer platform posts and product updates.",
    url: "https://devblogs.microsoft.com/",
    sourceType: "STRUCTURED",
    category: "product-updates",
  },
  {
    id: "aws-news-blog",
    title: "AWS News Blog",
    description: "AWS launch announcements and cloud platform updates.",
    url: "https://aws.amazon.com/blogs/aws/feed/",
    sourceType: "RSS",
    category: "product-updates",
  },
  {
    id: "azure-updates",
    title: "Azure Updates",
    description: "Microsoft Azure product update feed.",
    url: "https://azurecomcdn.azureedge.net/en-us/updates/feed/",
    sourceType: "RSS",
    category: "product-updates",
  },
  {
    id: "google-cloud-blog",
    title: "Google Cloud Blog",
    description: "Google Cloud product and engineering updates.",
    url: "https://cloud.google.com/blog/rss",
    sourceType: "RSS",
    category: "product-updates",
  },
  {
    id: "boss-zhipin",
    title: "BOSS 直聘",
    description: "Domestic China job listings and hiring signals from BOSS Zhipin.",
    url: "https://www.zhipin.com/web/geek/job",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "zhilian-zhaopin",
    title: "智联招聘",
    description: "Broad China recruiting listings from Zhaopin search.",
    url: "https://sou.zhaopin.com/",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "51job",
    title: "前程无忧 51job",
    description: "China job listings from 51job search pages.",
    url: "https://we.51job.com/pc/search",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "liepin",
    title: "猎聘",
    description: "Mid-to-senior China hiring listings and company recruitment signals.",
    url: "https://www.liepin.com/zhaopin/",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "lagou",
    title: "拉勾招聘",
    description: "Internet and technology hiring listings from Lagou.",
    url: "https://www.lagou.com/wn/jobs",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "maimai-jobs",
    title: "脉脉招聘",
    description: "Professional network hiring signals from Maimai jobs.",
    url: "https://maimai.cn/jobs/",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "remotejobscn",
    title: "Remote Jobs China",
    description: "Chinese remote-first engineering and product roles.",
    url: "https://remotejobscn.com/",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "wellfound-remote",
    title: "Wellfound Remote Jobs",
    description: "Startup-focused remote job listings.",
    url: "https://wellfound.com/remote",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "we-work-remotely",
    title: "We Work Remotely",
    description: "Large public remote job board for engineering and design.",
    url: "https://weworkremotely.com/remote-jobs",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "remoteok-dev",
    title: "RemoteOK Dev Jobs",
    description: "Developer-focused remote jobs with fast-moving listings.",
    url: "https://remoteok.com/remote-dev-jobs",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "remotive-software-dev",
    title: "Remotive Software Dev Jobs",
    description: "Remote software engineering roles from a curated board.",
    url: "https://remotive.com/remote-jobs/software-dev",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "yc-jobs",
    title: "Y Combinator Jobs",
    description: "Startup hiring signals from the YC company network.",
    url: "https://www.ycombinator.com/jobs",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
  {
    id: "hacker-news-jobs",
    title: "Hacker News Jobs",
    description: "Community-curated hiring and monthly startup job threads.",
    url: "https://news.ycombinator.com/jobs",
    sourceType: "STRUCTURED",
    category: "jobs",
  },
];

export function getSourcePresetById(presetId: string): SourcePreset | null {
  return sourcePresets.find((preset) => preset.id === presetId) ?? null;
}
