/// <reference types="vitest/globals" />

import { renderHtmlPushDocument } from "@/lib/html-push-render";
import type { HtmlPushModule } from "@/lib/store";
import { makeTopicRecord } from "./helpers/records";

function render(
  enabledModules: HtmlPushModule[] = ["summary", "key_content", "citations"],
) {
  return renderHtmlPushDocument({
    content: {
      title: "AI <script>alert(1)</script>",
      subtitle: "Daily summary",
      summary: "Summary <script>alert(1)</script>",
      keyPoints: [
        {
          title: "Launch",
          body: "New capability",
          url: "javascript:alert(1)",
        },
      ],
      aiConclusion: "Worth watching.",
      trendChanges: ["More agents"],
      recommendedActions: ["Track adoption"],
      citations: [
        { label: "Safe", url: "https://example.com" },
        { label: "Unsafe", url: "javascript:alert(1)" },
      ],
    },
    topic: makeTopicRecord(),
    contentType: "brief",
    contentId: "brief-1",
    stylePreset: "minimal_news",
    enabledModules,
    generatedAt: new Date("2026-05-25T00:00:00.000Z"),
  });
}

describe("HTML push renderer", () => {
  it("renders a complete escaped HTML document", () => {
    const html = render();

    expect(html).toContain("<!doctype html>");
    expect(html).toContain("Generated by Inflowee");
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
    expect(html).not.toContain("<script>");
  });

  it("does not render unsafe links", () => {
    const html = render();

    expect(html).toContain("https://example.com/");
    expect(html).not.toContain("javascript:alert");
  });

  it("omits disabled modules", () => {
    const html = render(["summary"]);

    expect(html).not.toContain("Key Content");
    expect(html).not.toContain("Sources");
  });

  it("renders distinct preset CSS", () => {
    const topic = makeTopicRecord();
    const base = {
      content: {
        title: "AI update",
        subtitle: "Daily summary",
        summary: "Summary",
        keyPoints: [],
        trendChanges: [],
        recommendedActions: [],
        citations: [],
      },
      topic,
      contentType: "brief" as const,
      contentId: "brief-1",
      enabledModules: ["summary"] as HtmlPushModule[],
      generatedAt: new Date("2026-05-25T00:00:00.000Z"),
    };

    expect(
      renderHtmlPushDocument({ ...base, stylePreset: "minimal_news" }),
    ).not.toBe(
      renderHtmlPushDocument({ ...base, stylePreset: "tech_radar" }),
    );
  });
});
